uses: jpetrucciani/mypy-check@master

# or specify a path!
uses: jpetrucciani/mypy-check@master
with:
  path: '.'


# or specify additional mypy flags!
uses: jpetrucciani/mypy-check@master
with:
  mypy_flags: '--config-file .mypy.ini'