name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync
      - name: Run tests with pytest
        run: |
          uv run coverage run -m pytest -v tests/tests.py --junitxml=results/wordchain/test.xml && uv run coverage xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()    
        with:
          name: Tests            
          path: results/wordchain/test.xml
          reporter: java-junit 
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          badge: true
          filename: coverage/coverage.xml
          fail_below_min: true
          format: markdown
          indicators: true
          hide_branch_rate: false
          hide_complexity: true
          output: file
          thresholds: '60 80'
      - name: Code Coverage Markdown
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
